/*
 * This is our main form all frames open above this frame with clicking the menu
 * 
 * 
 */
package programming2.assignment2;

import java.awt.Dialog.ModalityType;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @Authors:
 * Nikolay Nikolov,Behnaz Akbariafshar, Ali Torabi, 
 * Nathalie Desrosiers, Domenic Palucci
 */
public class MarinaMenager extends JFrame {
    private Object f;

    /**
     * Creates new form MarinaMenager
     */
    public MarinaMenager() {
        initComponents();
        try {
    		setContentPane(new JLabel(new ImageIcon(ImageIO.read(new File("Bradshaw_Marina.jpg")))));
    	} catch (IOException e) {
    		e.printStackTrace();
    	}
    	pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu = new javax.swing.JMenuBar();
        menuSystem = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        menuSettings = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuAbout = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();
        menuCustomer = new javax.swing.JMenu();
        menuCustomerNew = new javax.swing.JMenuItem();
        menuCustomerSearch = new javax.swing.JMenuItem();
        menuLease = new javax.swing.JMenu();
        menuLeaseNew = new javax.swing.JMenuItem();
        menuLeaseSearch = new javax.swing.JMenuItem();
        menuBoats = new javax.swing.JMenu();
        menuBoatNew = new javax.swing.JMenuItem();
        menuBoatSearch = new javax.swing.JMenuItem();
        menuSlipInfo = new javax.swing.JMenu();
        menuDocInfo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        aboutProject = new javax.swing.JMenuItem();
        aboutOurTeam = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shining Lake Marina lease Application");
        getContentPane().setLayout(null);

        menuSystem.setText("System");

        menuOpen.setText("Open...");
        menuSystem.add(menuOpen);

        menuSettings.setText("Settings...");
        menuSystem.add(menuSettings);
        menuSystem.add(jSeparator1);

        menuAbout.setText("About");
        menuSystem.add(menuAbout);

        menuHelp.setText("Help");
        menuSystem.add(menuHelp);
        menuSystem.add(jSeparator2);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuSystem.add(menuExit);

        MainMenu.add(menuSystem);

        menuCustomer.setText("Customer");

        menuCustomerNew.setText("New Customer...");
        menuCustomerNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCustomerNewActionPerformed(evt);
            }
        });
        menuCustomer.add(menuCustomerNew);

        menuCustomerSearch.setText("Search Customer...");
        menuCustomerSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCustomerSearchActionPerformed(evt);
            }
        });
        menuCustomer.add(menuCustomerSearch);

        MainMenu.add(menuCustomer);

        menuLease.setText("Lease");

        menuLeaseNew.setText("New Lease...");
        menuLeaseNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLeaseNewActionPerformed(evt);
            }
        });
        menuLease.add(menuLeaseNew);

        menuLeaseSearch.setText("Search Lease...");
        menuLease.add(menuLeaseSearch);

        MainMenu.add(menuLease);

        menuBoats.setText("Boats");

        menuBoatNew.setText("New Boat...");
        menuBoatNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBoatNewActionPerformed(evt);
            }
        });
        menuBoats.add(menuBoatNew);

        menuBoatSearch.setText("Search Boat...");
        menuBoats.add(menuBoatSearch);

        MainMenu.add(menuBoats);

        menuSlipInfo.setText("Dock");

        menuDocInfo.setText("Menage Docks...");
        menuDocInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDocInfoActionPerformed(evt);
            }
        });
        menuSlipInfo.add(menuDocInfo);

        jMenuItem1.setText("Menage Slips...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuSlipInfo.add(jMenuItem1);

        MainMenu.add(menuSlipInfo);

        jMenu1.setText("About");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        aboutProject.setText("Project");
        aboutProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutProjectActionPerformed(evt);
            }
        });
        jMenu1.add(aboutProject);

        aboutOurTeam.setText("Our Team");
        aboutOurTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutOurTeamActionPerformed(evt);
            }
        });
        jMenu1.add(aboutOurTeam);

        MainMenu.add(jMenu1);

        setJMenuBar(MainMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuCustomerNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCustomerNewActionPerformed
        AddNewCustomer addCustomer=new AddNewCustomer();
        addCustomer.setAlwaysOnTop(true);
        addCustomer.setVisible(true);
    }//GEN-LAST:event_menuCustomerNewActionPerformed

    private void menuCustomerSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCustomerSearchActionPerformed
        CustomersList customerList=new CustomersList();
        customerList.setAlwaysOnTop(true);
        customerList.setVisible(true);
    }//GEN-LAST:event_menuCustomerSearchActionPerformed

    private void menuBoatNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBoatNewActionPerformed
       JOptionPane.showMessageDialog(null,"please first Go to the Customer Form and fill" +
"  information"
                ,"attention",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuBoatNewActionPerformed

    private void menuLeaseNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLeaseNewActionPerformed
        LeaseGUI leaseG=new LeaseGUI();
        //leaseG.getFrmLeaseABoat().setAlwaysOnTop(true);
        leaseG.getFrmLeaseABoat().setVisible(true);
    }//GEN-LAST:event_menuLeaseNewActionPerformed

    private void menuDocInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDocInfoActionPerformed
         FormSelectSlip slipG=new FormSelectSlip();
        //leaseG.getFrmLeaseABoat().setAlwaysOnTop(true);
        slipG.setVisible(true);
    }//GEN-LAST:event_menuDocInfoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FormSelectSlip slipG=new FormSelectSlip();
        //leaseG.getFrmLeaseABoat().setAlwaysOnTop(true);
        slipG.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void aboutProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutProjectActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null," Bradshaw rents boat slips to customers on  Lake and needs "
                + "a system to track customers, boats, slips, and leases","assignment2",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutProjectActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void aboutOurTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutOurTeamActionPerformed
        
          JOptionPane.showMessageDialog(null," our team : Behnaz,Ali,Nikolay," +
"  Nathalie,Domenic"
                ,"Team Members",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutOurTeamActionPerformed
     

    /**
     * @param args the command line arguments
     */
   
    
    
   private JPanel mainPanel = new JPanel();
    private JDialog modalDialog;
    private JDialog nonModalDialog;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MainMenu;
    private javax.swing.JMenuItem aboutOurTeam;
    private javax.swing.JMenuItem aboutProject;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuBoatNew;
    private javax.swing.JMenuItem menuBoatSearch;
    private javax.swing.JMenu menuBoats;
    private javax.swing.JMenu menuCustomer;
    private javax.swing.JMenuItem menuCustomerNew;
    private javax.swing.JMenuItem menuCustomerSearch;
    private javax.swing.JMenuItem menuDocInfo;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuHelp;
    private javax.swing.JMenu menuLease;
    private javax.swing.JMenuItem menuLeaseNew;
    private javax.swing.JMenuItem menuLeaseSearch;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenuItem menuSettings;
    private javax.swing.JMenu menuSlipInfo;
    private javax.swing.JMenu menuSystem;
    // End of variables declaration//GEN-END:variables
}
