/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addition;

import java.awt.Container;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import javax.swing.*;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
/**
 *
 * @author student
 */
public class RectangleAppThree extends JFrame {
    // name constant will be used within tje class RectangleAppOne
    private static final int WIDTH = 400 ;
    private static final int HEIGHT = 300 ;
    private static final int WIDTH_X = 400 ;
    private static final int HEIGHT_Y = 400 ;
    
    // Create four JLabel objects
    private JLabel lengthL, widthL, areaL, perimeterL;
    
    // Create four JTextField objects
    private JTextField lengthTF, widthTF, areaTF, perimeterTF;

    // Create two JButton objects
    private JButton calculate, exit;
    
    // Default constractor
    public RectangleAppThree() {
        setTitle("Area and perimeter of the Rectangle One");
        setSize(WIDTH, HEIGHT);
        setLocation(WIDTH_X, HEIGHT_Y);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);

        // initialize four JLabel
        lengthL = new JLabel("Enter the length:", SwingConstants.RIGHT);
        widthL = new JLabel("Enter the width:", SwingConstants.RIGHT);
        areaL = new JLabel("Area:", SwingConstants.RIGHT);
        perimeterL = new JLabel("Perimeter:", SwingConstants.RIGHT);

        // initialize four JTextField
        lengthTF = new JTextField(10);
        widthTF = new JTextField(10);
        areaTF = new JTextField(10);
        perimeterTF = new JTextField(10);

        // initialize four JTextField
        calculate = new JButton("Calculate");
        exit = new JButton("Exit");

        // Declaire a reference variable of the container
        // and get the method getContentPane of the window
        Container pane = getContentPane();
        
        //Set the layout to GridLayout
        pane.setLayout(new GridLayout(5,2));
        
        // Add the labels and TextFields and JButtons to the pane container
        pane.add(lengthL);
        pane.add(lengthTF);
        pane.add(widthL);
        pane.add(widthTF);
        
        pane.add(areaL);
        pane.add(areaTF);
        pane.add(perimeterL);
        pane.add(perimeterTF);
        
        pane.add(calculate);
        pane.add(exit);
        
        calculate.addActionListener(new CalculateButtonHandler();

    }//end constructor RectangleAppOne
    // main method

    // Create the class CalculateButtonHandler to handle 
    // the event generated by clicking the button calculate
    // this class is created on the top of the interface ActionListener
    private CalculateButtonHandler implements ActionListener {
        public void actionPerformed(ActionEvent e){
            // add code to calculate the area and perimeter and display these values
            double width, height, area, perimeter;
            width = Double.parseDouble(lengthTF.getText());
            height = Double.parseDouble(widthTF.getText());
            areaTF.setText(String.valueOf( width*height ));
            perimeterTF.setText(String.valueOf(2 * (width + height)));
        }
    }// end class CalculateButtonHandler

    public static void main(String[] args) {
        RectangleAppThree rectThree = new RectangleAppThree();
        rectThree.setVisible(true);
//        rectOne.
    }// end main method

}// end class RectangleAppOne
